name: exceptions
description: A new Flutter package project.
version: 0.4.2
author:
homepage:

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  http: '^1.1.0'

dev_dependencies:
  test: ^1.17.0
